version: "3"

services:

  zookeeper:
    image: zookeeper:3.4.11
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
       - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "ticks:10:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  message-broker:
    image: redis:alpine3.8
    ports:
      - "6379:6379"
  flower:
    image: crgwbr/docker-celery-flower
    environment:
      CELERY_BROKER_URL: redis://message-broker:6379/0
    ports:
      - "5555:5555"
    command: flower --port=5555
  producer:
    build:
      context: producer
    volumes:
      - ./producer:/app
  consumer:
    build:
      context: consumer
    volumes:
      - ./consumer:/app
  worker:
    build:
      context: worker
    volumes:
      - ./worker:/app
